name: iOS Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 选择 Xcode 版本
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: 安装 CocoaPods 依赖项
        run: pod install
        working-directory: Listen1

      - name: 构建应用
        run: |
          xcodebuild clean build \
            -workspace Listen1.xcworkspace \
            -scheme Listen1 \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
        working-directory: Listen1

      - name: 导出未签名的 IPA 文件
        run: |
          xcodebuild -exportArchive \
            -archivePath build/Listen1.xcarchive \
            -exportPath build/ \
            -exportOptionsPlist exportOptions.plist
        working-directory: Listen1

      - name: 上传 IPA 文件
        uses: actions/upload-artifact@v4
        with:
          name: Listen1.ipa
          path: Listen1/build/Listen1.ipa
