name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 安装 Yarn
        run: npm install -g yarn

      - name: 安装项目依赖
        run: yarn install

      - name: 安装 CocoaPods 依赖
        run: pod install
        working-directory: ios

      - name: 构建 iOS 应用
        run: |
          xcodebuild clean build \
            -workspace ios/Listen 1.xcworkspace \
            -scheme Listen 1 \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath ios/build
